[package]
name = "tracing-texray"
version = "0.1.0"
edition = "2018"
authors = ["russell.r.cohen@gmail.com"]
license = "MIT"

[dependencies]
tracing-subscriber = "0.3.5"
tracing = "0.1.29"
lazy_static = "1.4.0"
term_size = "0.3.2"
